name: workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - germansentiment
  - pip:
      - streamlit
      - transformers
      - torch
      - torchvision
      